# Generated by Django 6.1.1 on 2026-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('id', 'Identification'), ('academic', 'Academic'), ('certificate', 'Certification'), ('cv', 'CV/Resume'), ('reference', 'Reference Letter'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
