# Generated by Django 6.1.1 on 2026-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encrypted_file_key',
            field=models.TextField(blank=True),
        ),
    ]
